name: Continuous Deployment (Prod)

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/argo-cd-app:${{ github.sha }}

      - name: Checkout argo-cd-app
        uses: actions/checkout@v4
        with:
          repository: Yogesh011-R/argo-cd-app
          token: ${{ secrets.PAT }}
          path: argo-cd-app

      - name: Update image tag in manifest
        run: |
          cd argo-cd-app

          sed -i "s|image: .*/argo-cd-app:.*|image: ${{ secrets.DOCKER_USERNAME }}/argo-cd-app:${{ github.sha }}|" ops/manifest.yml

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

          git add manifest.yml
          git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes"
          git push origin main
