name: Continuous Deployment (Prod)

on:
  push:
    branches: ['main']

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/argo-cd-app:${{ github.sha }}

      - name: Clone staging-ops repo, update image tags, and push tags
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          echo ${{github}}
          git clone https://github.com/Yogesh011-R/argo-cd-app.git
          cd argo-deployment

          sed -i 's|image: ${{secrets.DOCKER_USERNAME}}/argo-cd-app:.*|image: ${{secrets.DOCKER_USERNAME}}/argo-cd-app:${{ github.sha }}|' manifest.yml

          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update image tags to ${{ github.sha }}"
          git push https://${PAT}@github.com/100xdevs-cohort-3/argo-deployment.git main
